from pathlib import Path

SCRIPT_DIR = Path(__file__).parent
DATABASE_DIR = SCRIPT_DIR / 'databases'
DATABASE_DIR.mkdir(exist_ok=True)

ROOMS = [
	"Aerary",
	"Air shower",
	"Aircraft cabin",
	"Airport lounge",
	"Aisle",
	"Almonry",
	"Anechoic chamber",
	"Apodyterium",
	"Arizona room",
	"Assembly hall",
	"Atrium",
	"Attic",
	"Auditorium",
	"Aula regia",
	"Ballroom",
	"Bang",
	"Banishment room",
	"Bank vault",
	"Banking hall",
	"Banquet hall",
	"Basement",
	"Bathroom",
	"Battery room",
	"Bedroom",
	"Billiard room",
	"Bonus room",
	"Boudoir",
	"Breezeway",
	"Buttery",
	"Cabinet",
	"Cafeteria",
	"Caldarium",
	"Calefactory",
	"Castle chapel",
	"Central apparatus room",
	"Changing room",
	"Church hall",
	"Church porch",
	"Classroom",
	"Cleanroom",
	"Cloakroom",
	"Closet",
	"Committee room",
	"Common room",
	"Companionway",
	"Computer lab",
	"Conference hall",
	"Conservatory",
	"Control room",
	"Conversation pit",
	"Corner office",
	"Count room",
	"Counting house",
	"Courtroom",
	"Cry room",
	"Crypt",
	"Cryptoporticus",
	"Cubiculum",
	"Cyzicene hall",
	"Darbazi",
	"Dark room",
	"Darkroom",
	"Data room",
	"Den",
	"Dewaniya",
	"Dining room",
	"Diwan-khane",
	"Drawing room",
	"Drying room",
	"Dungeon",
	"Electrical room",
	"Equatorial room",
	"Equipment room",
	"Execution chamber",
	"Fainting room",
	"Family room",
	"First aid room",
	"Frigidarium",
	"Function hall",
	"Furnace room",
	"Garden office",
	"Garderobe",
	"Garret",
	"Genkan",
	"Ghorfa",
	"Granary",
	"Great chamber",
	"Great hall",
	"Great room",
	"Green room",
	"Hall",
	"Hallway",
	"Harem",
	"Hidden compartment",
	"Honeymoon suite",
	"Inglenook",
	"Kitchen",
	"Laconicum",
	"Lactation room",
	"Lanai",
	"Larder",
	"Laundry room",
	"Living room",
	"Lobby",
	"Locker room",
	"Loft",
	"Long gallery",
	"Lumber room",
	"Luxury box",
	"Maashaus",
	"Mail services center",
	"Mailroom",
	"Majlis",
	"Man cave",
	"Master control",
	"Mechanical floor",
	"Mechanical room",
	"Megaron",
	"Mehmaan khana",
	"Mission control center",
	"Mizuya",
	"Monastic cell",
	"Money room",
	"Musalla",
	"Music rehearsal space",
	"Network operations center",
	"Nilavara",
	"Nursery",
	"Oecus",
	"Office",
	"Opisthodomos",
	"Padded cell",
	"Pantry",
	"Parlour",
	"Period room",
	"Pinacotheca",
	"Portego",
	"Porters' lodge",
	"Porticus",
	"Presidential suite",
	"Priest hole",
	"Print room",
	"Prison cell",
	"Psychomanteum",
	"Public toilet",
	"Qa'a",
	"Quiet room",
	"Railway refreshment room",
	"Rain porch",
	"Recreation room",
	"Refectory",
	"Reredorter",
	"Riding hall",
	"Room number",
	"Roomsharing",
	"Root cellar",
	"Rotunda",
	"Sacristy",
	"Safe room",
	"Sauna",
	"Screened porch",
	"Secret passage",
	"Semi-basement",
	"Sensitive compartmented information facility",
	"Servants' hall",
	"Servants' quarters",
	"Server room",
	"Shoin",
	"Showroom",
	"Sky lobby",
	"Skyway",
	"Sleeping porch",
	"Slick (hiding place)",
	"Slype",
	"Small office/home office",
	"Smoking room",
	"Solar",
	"Staffroom",
	"Staircase tower",
	"State room",
	"Still room",
	"Storage room",
	"Storm cellar",
	"Stube",
	"Student lounge",
	"Studio",
	"Study",
	"Sudatorium",
	"Suite",
	"Sunroom",
	"Tabagie",
	"Tablinum",
	"Tasting room",
	"Tepidarium",
	"Throne room",
	"Torture chamber",
	"Transmission control room",
	"Triclinium",
	"Undercroft",
	"Utility room",
	"Utility vault",
	"Vestibule",
	"Waiting room",
	"Walk-in closet",
	"Washitsu",
	"Whispering gallery",
	"Wine cellar",
	"Wiring closet"
]
